### ISSUE TITLE
How to get it to sound like Tom Snively's 9C14.5 ? 

### ISSUE THREAD

**Issue by youssefavx** [EnigmaCurry/midi-livecode#1]
I want to replicate 9C14.5 from Tom's app [here](https://www.tomsnively.com/mmb/)

However, when I try something like: 

`molecular_music_box(seed="9C14.5", loops=16, bars=4, scale=ib.Scale.major, octave=3, bpm=120, delay=True, scale_rule=None)`

The timing is very different and does not sound alike at all. 

For some reason it only sounds like it initially (first 8 seconds or so) when the delay is set to False. 

This is with (on Tom's app): Key: C, Loop Length: 32, Tempo: 120, Initial Length: 9, Initial Note: C3, Second Length: 14.5

**Comment by EnigmaCurry** [comment]
You're right the looping is off in the second loop, I will work on fixing it

**Comment by EnigmaCurry** [comment]
I think I have it fixed in https://github.com/EnigmaCurry/midi-livecode/commit/20a07dbdee9e5a94777eae133f30fe368cc450b8

Here are the settings used: 

https://github.com/EnigmaCurry/midi-livecode/blob/20a07dbdee9e5a94777eae133f30fe368cc450b8/timelines.py#L38-L39

Let me know if its still off in any way. Thanks!

**Comment by youssefavx** [comment]
Awesome! Can't wait to try it. 

I'm getting this error when I run livecode.py: 

```
  File "livecode.py", line 11, in <module>
    import timelines
  File "/Users/josephvanrowe/Documents/midi-livecode/timelines.py", line 6, in <module>
    from isobar.io.midifile import MidiFileOut
```

Oh! I think I found the problem - I didn't do pip3 install -r requirements.txt 

Edit: That fixed it

**Comment by youssefavx** [comment]
Hallelujah! Working excellently so far! My god....this is amazing. Thanks again!

**Comment by EnigmaCurry** [comment]
Great! Let me know if you discover anything cool 😸👍

**Comment by youssefavx** [comment]
Will do!
